### ISSUE TITLE
Twitter to X: Please replace icon with "X", change text to "Twitter (X)", etc.

### ISSUE THREAD

**Issue by lsthompson** [jelleroorda/social-divi#3]
Can keep internal ref/name the same. Mostly the icon.

**Comment by jelleroorda** [comment]
Hi Luke,

I've noticed that the X brand icon is not available for font awesome 5 (which is what I'm currently using to test).

What version are you currently using? Not sure what would be the best way to go about this; it would probably require a v2 of the plugin. Currently it's using FA5 with `fab fa-icon-name`, but that would all need to be converted to `fa-brands fa-icon-name`.

I think putting out a v2 with FA6 would additionally require people to set up a FA account + their kits. As far as I have seen there is a limited "free plan".

Any thoughts?

**Comment by Zodiac1978** [comment]
Why don't using the "ETmodules" font instead. This would solve the dependency for the Font Awesome plugin and you have the X icon already.

**Comment by jelleroorda** [comment]
Hi Torsten, thanks for the suggestion.

Having a [quick look](https://www.elegantthemes.com/blog/resources/elegant-icon-font#complete-set-and-unicode-reference-guide) at the available icons it doesn't seem that all icons are available that the plugin currently supports (for example: telegram, tiktok, twitch to name a few). 

However, dropping Fontawesome as a dependency and going for another (open source) icon library might be a good idea going forward.

**Comment by Zodiac1978** [comment]
The page is not up-to-date. I just checked the Social Media module in the recent Divi and all three are supported.

This is the complete list:
Amazon
Bandcamp
Behance
BitBucket
Buffer
dribbble
Facebook
Flickr
FlipBoard
Foursquare
GitHub
Goodreads
Google
Houzz
Instagram
Itunes
Last.fm
Linie
LinkedIn
Medium
Meetup
MySpace
Odnoklassniki
Patreon
Periscope
Pinterest
Quora
Reddit
ResearchGate
RSS
skype
Snapchat
SoundCloud
Spotify
Steam
Telegram
TikTok
TripAdvisor
tumblr
Twitch
X
Vimeo
VK
Weibo
Whatsapp
XING
Yelp
Youtube

But compared to your list, there are indeed some missing:
Apple, Xing, Discord

**Comment by lsthompson** [comment]
Elegant Themes have updated it in the core footer icon set.

So this makes me wonder if you could inherit that one instead of sourcing from FA?

**Comment by techsurrusr** [comment]
On the above list https://rumble.com/ is missing.

**Comment by Zodiac1978** [comment]
It looks like Divi is using Fontawesome for some icons itself (for example TikTok). It is bundled since Version 4.13 (11-04-2021) in the folder `/core/admin/fonts/fontawesome/`.

**Comment by jelleroorda** [comment]
Migrating away to built-in icons in Divi would be a good option. I don't see the X icon though. Maybe someone can enlighten me? I tried a check in the text field through the visual editor.

![Screenshot 2024-12-04 at 15 25 47](https://github.com/user-attachments/assets/aaab9b81-3af1-4853-8f2c-79642a9bca37)

**Comment by Zodiac1978** [comment]
It is a mixture. For some icons Divi uses the FA Brands icons and for some ETModules.
I just used the Icons module and looked at the CSS for the "X" icon:

```css
.et_pb_social_icon a.icon::before {
  font-family: ETmodules;
  speak: none;
  font-style: normal;
  font-weight: 400;
  font-variant: normal;
  text-transform: none;
  line-height: 1;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-shadow: 0 0;
  direction: ltr;
}
.et-social-twitter a.icon::before {
  content: "\e094";
}
```

For TikTok (for example) it just adds one line to switch to the other font:

```css
.et-social-tiktok a.icon::before {
  content: "\E07B";
}
.et-pb-social-fa-icon a.icon::before {
  font-family: FontAwesome;
}
```
